name: Flutter Build APK

on:
  push:
    branches:
      - main  # اختر الفرع الذي تريد البناء عند تحديثه

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # 3. Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 4. Build APK
      - name: Build APK
        run: flutter build apk --release

      # 5. Upload APK as Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Flutter APK
          path: build/app/outputs/flutter-apk/app-release.apk
